name: Build & Publish Release APK

on:
  push:
    tags:
      - 'Release*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Setup Java JDK
      uses:
        actions/setup-java@v4.2.1
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Adapt build.gradle to make only Unsigned release
      run: sed -i -e 's~^[ ]*signingConfig[ ]*sign~//signingConfig sign~' build.gradle
    - name: Build Release APK
      run: ./gradlew build

    - name: Upload a Build Artifact for phone/table
      uses: actions/upload-artifact@v4.3.4
      with:
        name: Squore.phone.apk
        path: build/outputs/apk/phoneTabletPost23/release/Squore-phoneTabletPost23-release.apk

    - name: Upload a Build Artifact for wearOs
      uses: actions/upload-artifact@v4.3.4
      with:
        name: Squore.wearOs.apk
        path: build/outputs/apk/wearOs/release/Squore-wearOs-release.apk

    #- name: Releasing using Hub
    #  uses: sangatdesai/release-apk@main
    #  env:
    #   GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   APP_FOLDER: app
